export const lowEnergyFeelings = [
  {
    label: "Peaceful",
    emoji: "(˘⌣˘)",
    color: "#00A3AF",
    colorHover: "#00919D",
  },
  {
    label: "Content",
    emoji: "(＾▽＾)",
    color: "#00A3AF",
    colorHover: "#00919D",
  },
  { label: "Sad", emoji: "(╥﹏╥)", color: "#87CEEB", colorHover: "#76BADB" },
  {
    label: "Tired",
    emoji: "(-_-) zZ",
    color: "#87CEEB",
    colorHover: "#76BADB",
  },
];

export const highEnergyFeelings = [
  {
    label: "Motivated",
    emoji: "(｡•̀ᴗ-)✧",
    color: "#FF91A4",
    colorHover: "#FF7F95",
  },
  {
    label: "Excited",
    emoji: "(*^‿^*)",
    color: "#FF91A4",
    colorHover: "#FF7F95",
  },
  {
    label: "Stressed",
    emoji: "(；￣Д￣)",
    color: "#FFB3A7",
    colorHover: "#FF9F93",
  },
  {
    label: "Anxious",
    emoji: "(⁄•⁄ω⁄•⁄)",
    color: "#FFB3A7",
    colorHover: "#FF9F93",
  },
];

export const adviceList = [
  "Take a deep breath and think positively",
  "Remember to take it one step at a time",
  "Give yourself permission to relax",
  "Be kind to yourself, always",
  "Set small, achievable goals",
  "Celebrate your successes, no matter how small",
  "Seek support from friends and family when needed",
  "Stay present and focus on the now",
  "Acknowledge your feelings without judgment",
  "Practice gratitude each day",
  "Find joy in the small things",
  "Let go of things you can't control",
  "Take time to do things you enjoy",
  "Stay connected with loved ones",
  "Get plenty of rest and eat well",
  "Stay active to boost your mood",
  "Challenge negative thoughts with positive ones",
  "Be patient with your progress",
  "Break tasks into manageable steps",
  "Spend time in nature to clear your mind",
  "Limit your time on social media",
  "Practice mindfulness or meditation",
  "Seek professional help if you're overwhelmed",
  "Remember, it's okay to ask for help",
  "Keep a journal to express your thoughts",
  "Stay hydrated to keep your mind sharp",
  "Set boundaries to protect your energy",
  "Focus on what you can change",
  "Forgive yourself for past mistakes",
  "Celebrate the person you are becoming",
  "Look for opportunities to help others",
  "Keep learning and growing",
  "Find strength in your struggles",
  "Embrace change as an opportunity",
  "Maintain a routine to give your day structure",
  "Find a hobby that relaxes you",
  "Listen to music that lifts your spirits",
  "Don't compare yourself to others",
  "Watch a movie that makes you feel good",
  "Read books that inspire you",
  "Seek out positive and uplifting stories",
  "Volunteer your time to feel more connected",
  "Plan something to look forward to",
  "Take a digital detox",
  "Use affirmations to boost your self-esteem",
  "Visualize your goals and dreams",
  "Practice compassion towards others",
  "Remind yourself of your strengths",
  "Avoid substances that alter your mood",
  "Seek joy, not perfection",
  "Explore your creative side",
  "Invest in your personal development",
  "Challenge yourself to step out of your comfort zone",
  "Adopt a pet for companionship and unconditional love",
  "Reflect on what you've learned from tough times",
  "Organize your space for a clearer mind",
  "Teach someone else a skill you're good at",
  "Attend workshops or classes to meet new people",
  "Create a vision board for your life",
  "Set a daily intention",
  "Practice deep breathing exercises",
  "Seek inspiration from role models",
  "Try yoga to reduce stress",
  "Smile more, it's good for your brain",
  "Thank your body for what it does for you",
  "Remember to laugh, it's healing",
  "Appreciate the present moment",
  "Prioritize self-care",
  "Find peace in letting things be",
  "Plan regular meet-ups with friends",
  "Embrace your uniqueness",
  "Nurture your spirit in whatever way feels right",
  "Acknowledge your growth",
  "Learn to love the journey, not just the destination",
  "Acknowledge small victories every day.",
  "Replace 'I must' with 'I choose' to empower yourself.",
  "Laugh often—it's a natural stress reliever.",
  "Make time for meditation, even if it's just a few minutes.",
  "Surround yourself with people who lift you up.",
  "Practice saying 'no' to things that drain your energy.",
  "Find beauty in the ordinary.",
  "Listen to your body and rest when you need to.",
  "Keep a gratitude diary to remind yourself of the good.",
  "Embrace your flaws—they make you unique.",
  "Focus on what you can control and let go of what you can't.",
  "Engage in creative activities to express yourself.",
  "Spend less time on things that don't bring you joy.",
  "Seek out silence to calm your mind.",
  "Remember, everyone's journey is different.",
  "Cut out comparisons—they steal your joy.",
  "Allow yourself to feel sad without guilt.",
  "Visualize your future success and work towards it.",
  "Unplug from digital devices periodically.",
  "Do something kind for someone else without expecting anything in return.",
  "Prioritize your mental health as much as your physical health.",
  "Accept that change is a part of life.",
  "Reframe failures as opportunities to learn.",
  "Set realistic expectations for yourself and others.",
  "Practice deep breathing to manage stress.",
  "Avoid people who undermine your self-esteem.",
  "Treat yourself with the same compassion you offer others.",
  "Limit caffeine and sugar to avoid energy crashes.",
  "Keep your living space tidy for a clearer mind.",
  "Plan a getaway to change your perspective.",
  "Stay curious and keep learning new things.",
  "Use affirmations to reinforce positive self-talk.",
  "Create routines that anchor your day positively.",
  "Be proactive about solving problems.",
  "Watch sunrises or sunsets to connect with nature.",
  "Choose to forgive others and free yourself from holding grudges.",
  "Invest time in your hobbies to nurture your soul.",
  "Attend therapy if you need professional support.",
  "Celebrate other people's successes with them.",
  "Face fears gradually to overcome them.",
  "Smile at strangers—small acts of kindness matter.",
  "Use art to express feelings when words are hard to find.",
  "Prepare for the day ahead the night before.",
  "Acknowledge your progress, no matter how small.",
  "Dedicate time to your personal growth.",
  "Share your feelings honestly with trusted people.",
  "Choose to be hopeful, even in difficult times.",
  "Set boundaries to protect your peace.",
  "Explore different ways to manage stress.",
  "Remember, taking a break is a part of productivity.",
  "Eat nutritious foods to boost your mood.",
  "Seek inspiration from people you admire.",
  "Challenge yourself with new experiences.",
  "Respect your limits and don't overcommit.",
  "Reflect on what happiness means to you.",
  "Build resilience by facing small challenges.",
  "Show gratitude to those who support you.",
  "Develop a positive morning routine.",
  "Read books that inspire personal growth.",
  "Replace fear of the unknown with curiosity.",
  "Learn to enjoy your own company.",
  "Cultivate patience; good things take time.",
  "Recognize when you need help and don't hesitate to ask for it.",
  "Commit to personal goals and review them regularly.",
  "Find strength in community and shared experiences.",
  "Balance solitude with social interactions for well-being.",
  "Explore mindfulness to enhance self-awareness.",
  "Celebrate life's simple pleasures.",
  "Remember that your best is enough.",
  "Embrace life's ups and downs with grace.",
  "Nurture relationships that make you feel good about yourself.",
  "Develop a mindset of abundance rather than scarcity.",
  "Be mindful of your media consumption and its effect on your mood.",
];
